// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.esijob.domain;

import es.uca.iw.esijob.domain.Contrato;
import es.uca.iw.esijob.domain.ContratoDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ContratoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ContratoDataOnDemand: @Component;
    
    private Random ContratoDataOnDemand.rnd = new SecureRandom();
    
    private List<Contrato> ContratoDataOnDemand.data;
    
    public Contrato ContratoDataOnDemand.getNewTransientContrato(int index) {
        Contrato obj = new Contrato();
        setNombre(obj, index);
        return obj;
    }
    
    public void ContratoDataOnDemand.setNombre(Contrato obj, int index) {
        String nombre = "nombre_" + index;
        if (nombre.length() > 45) {
            nombre = nombre.substring(0, 45);
        }
        obj.setNombre(nombre);
    }
    
    public Contrato ContratoDataOnDemand.getSpecificContrato(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Contrato obj = data.get(index);
        Integer id = obj.getId();
        return Contrato.findContrato(id);
    }
    
    public Contrato ContratoDataOnDemand.getRandomContrato() {
        init();
        Contrato obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return Contrato.findContrato(id);
    }
    
    public boolean ContratoDataOnDemand.modifyContrato(Contrato obj) {
        return false;
    }
    
    public void ContratoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Contrato.findContratoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Contrato' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Contrato>();
        for (int i = 0; i < 10; i++) {
            Contrato obj = getNewTransientContrato(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
