// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.esijob.domain;

import es.uca.iw.esijob.domain.Demandante;
import es.uca.iw.esijob.domain.DemandanteDataOnDemand;
import es.uca.iw.esijob.domain.Usuario;
import es.uca.iw.esijob.domain.UsuarioDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect DemandanteDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DemandanteDataOnDemand: @Component;
    
    private Random DemandanteDataOnDemand.rnd = new SecureRandom();
    
    private List<Demandante> DemandanteDataOnDemand.data;
    
    @Autowired
    UsuarioDataOnDemand DemandanteDataOnDemand.usuarioDataOnDemand;
    
    public Demandante DemandanteDataOnDemand.getNewTransientDemandante(int index) {
        Demandante obj = new Demandante();
        setDireccion(obj, index);
        setEmail(obj, index);
        setExperiencia(obj, index);
        setFecNac(obj, index);
        setFoto(obj, index);
        setIdusuario(obj, index);
        setNombre(obj, index);
        setResumenTray(obj, index);
        setSexo(obj, index);
        setTelefono(obj, index);
        setTrabajosDisp(obj, index);
        return obj;
    }
    
    public void DemandanteDataOnDemand.setDireccion(Demandante obj, int index) {
        String direccion = "direccion_" + index;
        if (direccion.length() > 256) {
            direccion = direccion.substring(0, 256);
        }
        obj.setDireccion(direccion);
    }
    
    public void DemandanteDataOnDemand.setEmail(Demandante obj, int index) {
        String email = "foo" + index + "@bar.com";
        if (email.length() > 256) {
            email = email.substring(0, 256);
        }
        obj.setEmail(email);
    }
    
    public void DemandanteDataOnDemand.setExperiencia(Demandante obj, int index) {
        String experiencia = "experiencia_" + index;
        if (experiencia.length() > 2048) {
            experiencia = experiencia.substring(0, 2048);
        }
        obj.setExperiencia(experiencia);
    }
    
    public void DemandanteDataOnDemand.setFecNac(Demandante obj, int index) {
        Date fecNac = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFecNac(fecNac);
    }
    
    public void DemandanteDataOnDemand.setFoto(Demandante obj, int index) {
        String foto = "foto_" + index;
        if (foto.length() > 64) {
            foto = foto.substring(0, 64);
        }
        obj.setFoto(foto);
    }
    
    public void DemandanteDataOnDemand.setIdusuario(Demandante obj, int index) {
        Usuario idusuario = usuarioDataOnDemand.getRandomUsuario();
        obj.setIdusuario(idusuario);
    }
    
    public void DemandanteDataOnDemand.setNombre(Demandante obj, int index) {
        String nombre = "nombre_" + index;
        if (nombre.length() > 128) {
            nombre = nombre.substring(0, 128);
        }
        obj.setNombre(nombre);
    }
    
    public void DemandanteDataOnDemand.setResumenTray(Demandante obj, int index) {
        String resumenTray = "resumenTray_" + index;
        if (resumenTray.length() > 1024) {
            resumenTray = resumenTray.substring(0, 1024);
        }
        obj.setResumenTray(resumenTray);
    }
    
    public void DemandanteDataOnDemand.setSexo(Demandante obj, int index) {
        String sexo = String.valueOf(index);
        if (sexo.length() > 1) {
            sexo = sexo.substring(0, 1);
        }
        obj.setSexo(sexo);
    }
    
    public void DemandanteDataOnDemand.setTelefono(Demandante obj, int index) {
        String telefono = "telefono_" + index;
        if (telefono.length() > 16) {
            telefono = telefono.substring(0, 16);
        }
        obj.setTelefono(telefono);
    }
    
    public void DemandanteDataOnDemand.setTrabajosDisp(Demandante obj, int index) {
        String trabajosDisp = "trabajosDisp_" + index;
        if (trabajosDisp.length() > 2048) {
            trabajosDisp = trabajosDisp.substring(0, 2048);
        }
        obj.setTrabajosDisp(trabajosDisp);
    }
    
    public Demandante DemandanteDataOnDemand.getSpecificDemandante(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Demandante obj = data.get(index);
        Integer id = obj.getId();
        return Demandante.findDemandante(id);
    }
    
    public Demandante DemandanteDataOnDemand.getRandomDemandante() {
        init();
        Demandante obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return Demandante.findDemandante(id);
    }
    
    public boolean DemandanteDataOnDemand.modifyDemandante(Demandante obj) {
        return false;
    }
    
    public void DemandanteDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Demandante.findDemandanteEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Demandante' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Demandante>();
        for (int i = 0; i < 10; i++) {
            Demandante obj = getNewTransientDemandante(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
