// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.esijob.prueba;

import es.uca.iw.esijob.prueba.Prueba;
import es.uca.iw.esijob.prueba.PruebaDataOnDemand;
import es.uca.iw.esijob.prueba.PruebaIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PruebaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PruebaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PruebaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PruebaIntegrationTest: @Transactional;
    
    @Autowired
    PruebaDataOnDemand PruebaIntegrationTest.dod;
    
    @Test
    public void PruebaIntegrationTest.testCountPruebas() {
        Assert.assertNotNull("Data on demand for 'Prueba' failed to initialize correctly", dod.getRandomPrueba());
        long count = Prueba.countPruebas();
        Assert.assertTrue("Counter for 'Prueba' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PruebaIntegrationTest.testFindPrueba() {
        Prueba obj = dod.getRandomPrueba();
        Assert.assertNotNull("Data on demand for 'Prueba' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Prueba' failed to provide an identifier", id);
        obj = Prueba.findPrueba(id);
        Assert.assertNotNull("Find method for 'Prueba' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Prueba' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PruebaIntegrationTest.testFindAllPruebas() {
        Assert.assertNotNull("Data on demand for 'Prueba' failed to initialize correctly", dod.getRandomPrueba());
        long count = Prueba.countPruebas();
        Assert.assertTrue("Too expensive to perform a find all test for 'Prueba', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Prueba> result = Prueba.findAllPruebas();
        Assert.assertNotNull("Find all method for 'Prueba' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Prueba' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PruebaIntegrationTest.testFindPruebaEntries() {
        Assert.assertNotNull("Data on demand for 'Prueba' failed to initialize correctly", dod.getRandomPrueba());
        long count = Prueba.countPruebas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Prueba> result = Prueba.findPruebaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Prueba' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Prueba' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PruebaIntegrationTest.testFlush() {
        Prueba obj = dod.getRandomPrueba();
        Assert.assertNotNull("Data on demand for 'Prueba' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Prueba' failed to provide an identifier", id);
        obj = Prueba.findPrueba(id);
        Assert.assertNotNull("Find method for 'Prueba' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPrueba(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Prueba' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PruebaIntegrationTest.testMergeUpdate() {
        Prueba obj = dod.getRandomPrueba();
        Assert.assertNotNull("Data on demand for 'Prueba' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Prueba' failed to provide an identifier", id);
        obj = Prueba.findPrueba(id);
        boolean modified =  dod.modifyPrueba(obj);
        Integer currentVersion = obj.getVersion();
        Prueba merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Prueba' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PruebaIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Prueba' failed to initialize correctly", dod.getRandomPrueba());
        Prueba obj = dod.getNewTransientPrueba(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Prueba' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Prueba' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Prueba' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PruebaIntegrationTest.testRemove() {
        Prueba obj = dod.getRandomPrueba();
        Assert.assertNotNull("Data on demand for 'Prueba' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Prueba' failed to provide an identifier", id);
        obj = Prueba.findPrueba(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Prueba' with identifier '" + id + "'", Prueba.findPrueba(id));
    }
    
}
