// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.esijob.prueba;

import es.uca.iw.esijob.prueba.Prueba;
import es.uca.iw.esijob.prueba.PruebaDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PruebaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PruebaDataOnDemand: @Component;
    
    private Random PruebaDataOnDemand.rnd = new SecureRandom();
    
    private List<Prueba> PruebaDataOnDemand.data;
    
    public Prueba PruebaDataOnDemand.getNewTransientPrueba(int index) {
        Prueba obj = new Prueba();
        setLogin(obj, index);
        setTipo(obj, index);
        return obj;
    }
    
    public void PruebaDataOnDemand.setLogin(Prueba obj, int index) {
        String login = "login_" + index;
        obj.setLogin(login);
    }
    
    public void PruebaDataOnDemand.setTipo(Prueba obj, int index) {
        Integer tipo = new Integer(index);
        obj.setTipo(tipo);
    }
    
    public Prueba PruebaDataOnDemand.getSpecificPrueba(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Prueba obj = data.get(index);
        Long id = obj.getId();
        return Prueba.findPrueba(id);
    }
    
    public Prueba PruebaDataOnDemand.getRandomPrueba() {
        init();
        Prueba obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Prueba.findPrueba(id);
    }
    
    public boolean PruebaDataOnDemand.modifyPrueba(Prueba obj) {
        return false;
    }
    
    public void PruebaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Prueba.findPruebaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Prueba' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Prueba>();
        for (int i = 0; i < 10; i++) {
            Prueba obj = getNewTransientPrueba(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
