// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.esijob.domain;

import es.uca.iw.esijob.domain.InscripcionPK;
import java.io.Serializable;

privileged aspect InscripcionPK_Roo_Serializable {
    
    declare parents: InscripcionPK implements Serializable;
    
    private static final long InscripcionPK.serialVersionUID = 1L;
    
}
