// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.esijob.domain;

import es.uca.iw.esijob.domain.PuestoPK;
import java.io.Serializable;

privileged aspect PuestoPK_Roo_Serializable {
    
    declare parents: PuestoPK implements Serializable;
    
    private static final long PuestoPK.serialVersionUID = 1L;
    
}
